/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ricar
 */
public class visual extends javax.swing.JFrame {

    /**
     * Creates new form visual
     */
    String ruta;
    private MetodosAvl avl;
    Graphics arbol;
    int x, y, x2, y2;
    public visual() {
        initComponents();
        this.avl=new MetodosAvl();
        setExtendedState(MAXIMIZED_BOTH);
        arbol = this.pnlGrafico.getGraphics();
        x = pnlGrafico.getWidth() / 2;
        y = pnlGrafico.getHeight() / 15;
        x2 = pnlGrafico.getWidth() / 10;
        y2 = pnlGrafico.getHeight() / 10;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        pnlRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarUsuarios = new javax.swing.JButton();
        btnCargarInformacion = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        cbxGenero = new javax.swing.JComboBox<>();
        btnVerArbol = new javax.swing.JButton();
        btnRepaint = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioBotones = new javax.swing.JTextField();
        btnRemoverUsuarios = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRealizarQueja = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnResumen = new javax.swing.JButton();
        pnlGrafico = new javax.swing.JPanel();
        lblMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));
        panelFondo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "RENT CAR S.A", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 3, 24), new java.awt.Color(102, 255, 102))); // NOI18N

        pnlRegistro.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3), "REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("USUARIO:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("EDAD:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRES:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("GENERO:");

        btnAgregarUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarUsuarios.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        btnAgregarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarUsuarios.setText("AGREGAR NUEVO USUARIO");
        btnAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuariosActionPerformed(evt);
            }
        });

        btnCargarInformacion.setBackground(new java.awt.Color(0, 0, 0));
        btnCargarInformacion.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        btnCargarInformacion.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarInformacion.setText("CARGAR UN ARCHIVO");
        btnCargarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarInformacionActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        txtNombres.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        txtEdad.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        cbxGenero.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otros" }));

        btnVerArbol.setBackground(new java.awt.Color(0, 0, 0));
        btnVerArbol.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        btnVerArbol.setForeground(new java.awt.Color(255, 255, 255));
        btnVerArbol.setText("VER ARBOL");
        btnVerArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArbolActionPerformed(evt);
            }
        });

        btnRepaint.setBackground(new java.awt.Color(0, 0, 0));
        btnRepaint.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        btnRepaint.setForeground(new java.awt.Color(255, 255, 255));
        btnRepaint.setText("LIMPIAR");
        btnRepaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlRegistroLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlRegistroLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRegistroLayout.createSequentialGroup()
                                    .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombres)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlRegistroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRepaint))))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarUsuarios)
                            .addGroup(pnlRegistroLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnCargarInformacion))
                            .addComponent(btnVerArbol))))
                .addGap(41, 41, 41))
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAgregarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerArbol)
                    .addComponent(btnRepaint))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3), "BOTONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("USUARIO:");

        txtUsuarioBotones.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        btnRemoverUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        btnRemoverUsuarios.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnRemoverUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverUsuarios.setText("REMOVER USUARIO");
        btnRemoverUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUsuariosActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR USUARIO");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRealizarQueja.setBackground(new java.awt.Color(0, 0, 0));
        btnRealizarQueja.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnRealizarQueja.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarQueja.setText("REALIZAR UNA QUEJA");
        btnRealizarQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarQuejaActionPerformed(evt);
            }
        });

        btnMostrar.setBackground(new java.awt.Color(0, 0, 0));
        btnMostrar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("MOSTRAR USUARIOS");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnResumen.setBackground(new java.awt.Color(0, 0, 0));
        btnResumen.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnResumen.setForeground(new java.awt.Color(255, 255, 255));
        btnResumen.setText("RESUMEN TOTAL");
        btnResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoverUsuarios)
                            .addComponent(btnMostrar)
                            .addGroup(pnlBotonesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscar)
                                    .addComponent(btnResumen))))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRealizarQueja)
                .addGap(65, 65, 65))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsuarioBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnRemoverUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizarQueja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResumen)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlGrafico.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 3), "VISUAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lblMostrar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGraficoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGraficoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graficarArbol(Graphics arbol, nodo raiz, int x, int y, int auxX, int auxY, int nivel){
        
        if(raiz!= null){
            //graficando las lineas
            arbol.setColor(Color.BLACK);
            if(raiz.izq != null){
                arbol.drawLine(x, y, x - auxX + (nivel * 2), y + auxY);
            }
            if(raiz.der != null){
                arbol.drawLine(x, y, x + auxX - (nivel * 2), y + auxY);
            }
            //graficando
            arbol.setColor(Color.YELLOW);
            arbol.fillRect(x-10, y-20, 40, 40);
            //arbol.fillOval(x - 10, y - 20, 40, 40);
            arbol.setColor(Color.BLACK);
            arbol.drawString(String.valueOf(raiz.info), x, y);
            //recursividad
            graficarArbol(arbol, raiz.izq, x - auxX, y + auxY, auxX + nivel * 2, auxY * 2, nivel + 2);
            graficarArbol(arbol, raiz.der, x + auxX, y + auxY, auxX - nivel * 2, auxY, nivel + 1);
        }
    }
    
    public void seleccionar_txt() {
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("txt", "txt");
        jf.setFileFilter(fi);
        int se = jf.showOpenDialog(this);

        if (se == 0) {
            this.ruta = jf.getSelectedFile().getAbsolutePath();
        }
    }
    
    private void btnAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosActionPerformed
        // TODO add your handling code here:
        try{
            String user, name, genero;
            int edad, queja=0;
            
            user=txtUsuario.getText();
            name=txtNombres.getText();
            edad=Integer.parseInt(txtEdad.getText());
            genero=cbxGenero.getSelectedItem().toString();
            queja++;
            usuarios nuevoUsuario = new usuarios(user, name, edad, genero, queja);
            avl.insertar(nuevoUsuario);         
                       
            arbol= this.pnlGrafico.getGraphics();
            graficarArbol(arbol, avl.getRaiz(), x, y, x2, y2, 1);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        txtUsuario.setText("");
        txtEdad.setText("");
        txtNombres.setText("");
    }//GEN-LAST:event_btnAgregarUsuariosActionPerformed

    private void btnCargarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarInformacionActionPerformed
        // TODO add your handling code here:
        try {
            this.seleccionar_txt();
            LecturaEscritura le = new LecturaEscritura(ruta);
            cargar c = new cargar(le.leer());
            avl = c.separar();

            graficarArbol(arbol, avl.getRaiz(), x, y, x2, y2, 1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCargarInformacionActionPerformed

    private void btnRemoverUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUsuariosActionPerformed
        // TODO add your handling code here:
        try{
            String user=txtUsuarioBotones.getText();
            if(avl.BuscarBooleano(user)==true){
                avl.eliminar(user);
                JOptionPane.showMessageDialog(null, "Se elimino el usuario");
            }else{
                lblMostrar.setText("No existe el usuario");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_btnRemoverUsuariosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            String user=txtUsuarioBotones.getText();
            if(avl.BuscarBooleano(user)==true){
                lblMostrar.setText(avl.BuscarString(user));
            }else{
                lblMostrar.setText("No existe el usuario...\nIngrese de nuevo");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        //txtUsuarioBotones.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRealizarQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarQuejaActionPerformed
        // TODO add your handling code here:
        try{
            String user=txtUsuarioBotones.getText();
            int valorQuejas=avl.Quejas(user);
            if(avl.BuscarBooleano(user)==true){
                if(valorQuejas>=5){
                    avl.eliminar(user);
                    lblMostrar.setText("El usuario "+user+" ah sido eliminado por tener 5 quejas...");
                }else{
                    lblMostrar.setText("Queja aumentada en el usuario: "+user);
                }
            }else{
                    lblMostrar.setText("No existe el usuario...");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnRealizarQuejaActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        try{
            String msg="";
            msg="<html>";
            msg+="Los usuarios son: <p>";

            msg+=avl.mostrarDatos();
            
            msg+="</html>";
            lblMostrar.setText(msg);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenActionPerformed
        // TODO add your handling code here:
        try{
            int quejaMayor=0;
            int quejaMenor=5;
            String msg="";

            msg="<html>";
            
            msg+="El resumen los usuarios de acuerdo a sus quejas son: <p>";
            msg+="El usuario con mayor quejas es: <p>";
            msg+=avl.buscarQuejaMayor(quejaMayor)+"<p>";
            msg+="El usuario con menor quejas es: <p>";
            msg+=avl.buscarQuejaMenor(quejaMenor)+"<p>";

            msg+="</html>";
            lblMostrar.setText(msg);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnResumenActionPerformed

    private void btnVerArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArbolActionPerformed
        // TODO add your handling code here:
        graficarArbol(arbol, avl.getRaiz(), x, y, x2, y2, 1);
    }//GEN-LAST:event_btnVerArbolActionPerformed

    private void btnRepaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepaintActionPerformed
        // TODO add your handling code here:
        this.pnlGrafico.repaint();
    }//GEN-LAST:event_btnRepaintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuarios;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarInformacion;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRealizarQueja;
    private javax.swing.JButton btnRemoverUsuarios;
    private javax.swing.JButton btnRepaint;
    private javax.swing.JButton btnResumen;
    private javax.swing.JButton btnVerArbol;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel lblMostrar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioBotones;
    // End of variables declaration//GEN-END:variables
}
